/**
 * Attributes Registry
 * Service managing the persistence of attributes in a local registry
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.attributeregistrymanagement.client.api

import it.pagopa.pdnd.interop.uservice.attributeregistrymanagement.client.model.Problem
import it.pagopa.pdnd.interop.uservice.attributeregistrymanagement.client.invoker._
import it.pagopa.pdnd.interop.uservice.attributeregistrymanagement.client.invoker.CollectionFormats._
import it.pagopa.pdnd.interop.uservice.attributeregistrymanagement.client.invoker.ApiKeyLocations._

object HealthApi {

  def apply(baseUrl: String = "https://gateway.interop.pdnd.dev/pdnd-interop-uservice-attribute-registry-management/}") = new HealthApi(baseUrl)
}

class HealthApi(baseUrl: String) {

  /**
   * Return ok
   * 
   * Expected answers:
   *   code 200 : Problem (successful operation)
   */
  def getStatus(): ApiRequest[Problem] =
    ApiRequest[Problem](ApiMethods.GET, baseUrl, "/status", "application/json")
      .withSuccessResponse[Problem](200)
      



}

