/**
 * Attributes Registry
 * Service managing the persistence of attributes in a local registry
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.attributeregistrymanagement.client.model

import it.pagopa.pdnd.interop.uservice.attributeregistrymanagement.client.invoker.ApiModel

case class AttributesResponse (
  attributes: Seq[Attribute]
) extends ApiModel

